<a href="https://colab.research.google.com/github/Insight-Syndicate/DSPL_GCW/blob/main/Model_building.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
#Import Necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# **Data Scalling**

## **Test**

In [21]:
#Access the dataset "clean_test"
clean_test = pd.read_csv("clean_test.csv")

In [22]:
clean_test

,Customer_ID,outlet_city,luxury_sales,fresh_sales,dry_sales,outlet_city_encoded
0,33574,Batticaloa,2686.50,3582.00,12537.00,1
1,10089,Batticaloa,1717.56,2576.34,9446.58,1
2,38329,Batticaloa,854.04,1242.24,5201.88,1
3,11376,Batticaloa,1638.12,2320.67,9282.68,1
4,12410,Batticaloa,1039.09,1518.67,5435.24,1
...,...,...,...,...,...,...
40744,33698,Wattala,3916.48,4161.26,3916.48,21
40745,4185,Wattala,3191.92,3004.16,3098.04,21
40746,28664,Wattala,3838.60,3951.50,3700.00,21
40747,11874,Wattala,4313.76,4183.04,4313.76,21
40748,11431,Wattala,4212.16,4212.16,4212.16,21

We are using the robust scaller since our data is skewed and luxury sales has outliers. Since this technique scales using the median and IQR it is best suited to deal with the skewness and the extreme values.

In [23]:
from sklearn.preprocessing import RobustScaler
# Identify numerical columns
numerical_columns = ['luxury_sales', 'fresh_sales', 'dry_sales']

# Initialize RobustScaler
DSPL_scaler = RobustScaler()

# Fit on training numerical data and transform both train & test
clean_test[numerical_columns] = DSPL_scaler.fit_transform(clean_test[numerical_columns])
clean_test

,Customer_ID,outlet_city,luxury_sales,fresh_sales,dry_sales,outlet_city_encoded
0,33574,Batticaloa,0.857034,0.041937,1.631090,1
1,10089,Batticaloa,-0.003695,-0.156121,1.057081,1
2,38329,Batticaloa,-0.770778,-0.418864,0.268678,1
3,11376,Batticaloa,-0.074264,-0.206474,1.026639,1
4,12410,Batticaloa,-0.606394,-0.364423,0.312022,1
...,...,...,...,...,...,...
40744,33698,Wattala,1.949650,0.156019,0.029930,21
40745,4185,Wattala,1.306009,-0.071865,-0.122086,21
40746,28664,Wattala,1.880468,0.114708,-0.010279,21
40747,11874,Wattala,2.302562,0.160308,0.103720,21
40748,11431,Wattala,2.212309,0.166043,0.084849,21

## **Train**

In [24]:
#Access the dataset "clean_train"
clean_train = pd.read_csv("clean_train.csv")

In [25]:
clean_train

,Customer_ID,outlet_city,luxury_sales,fresh_sales,dry_sales,cluster_catgeory,outlet_city_encoded
0,10493832.0,Kelaniya,1209.60,756.00,5292.00,4,11
1,10178643.0,Moratuwa,1590.12,1060.08,6007.12,1,13
2,10513916.0,Wattala,2288.88,1481.04,9155.52,4,19
3,10334589.0,Wattala,2274.94,1739.66,9099.76,4,19
4,10458365.0,Kelaniya,2345.49,2069.55,9243.99,4,11
...,...,...,...,...,...,...,...
774140,10197979.0,Gampaha,3893.40,3893.40,3448.44,3,4
774141,10494575.0,Katunayake,6095.86,5557.99,6275.15,3,10
774142,10565682.0,Colombo,5121.42,4820.16,4669.53,3,1
774143,10351977.0,Kandy,6311.76,6311.76,5940.48,3,9
774144,10637635.0,Negombo,5833.50,6027.95,6611.30,3,14

We are using the robust scaller since our data is skewed and luxury sales has outliers. Since this technique scales using the median and IQR it is best suited to deal with the skewness and the extreme values.

In [26]:
from sklearn.preprocessing import RobustScaler
# Identify numerical columns
numerical_columns = ['luxury_sales', 'fresh_sales', 'dry_sales']

# Initialize RobustScaler
DSPL_scaler = RobustScaler()

# Fit on training numerical data and transform both train & test
clean_train[numerical_columns] = DSPL_scaler.fit_transform(clean_train[numerical_columns])
clean_train

,Customer_ID,outlet_city,luxury_sales,fresh_sales,dry_sales,cluster_catgeory,outlet_city_encoded
0,10493832.0,Kelaniya,-0.449457,-0.514864,0.291089,4,11
1,10178643.0,Moratuwa,-0.111244,-0.454663,0.424165,1,13
2,10513916.0,Wattala,0.509826,-0.371322,1.010049,4,19
3,10334589.0,Wattala,0.497436,-0.320120,0.999672,4,19
4,10458365.0,Kelaniya,0.560142,-0.254809,1.026512,4,11
...,...,...,...,...,...,...,...
774140,10197979.0,Gampaha,1.935952,0.106275,-0.051979,3,4
774141,10494575.0,Katunayake,3.893537,0.435829,0.474042,3,10
774142,10565682.0,Colombo,3.027438,0.289754,0.175253,3,1
774143,10351977.0,Kandy,4.085433,0.585060,0.411764,3,9
774144,10637635.0,Negombo,3.660347,0.528871,0.536596,3,14