<a href="https://colab.research.google.com/github/Insight-Syndicate/DSPL_GCW/blob/main/Model_building.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Import Necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
# Original URL from Google Drive
url = 'https://drive.google.com/file/d/1KtSHNay_hiwqNUNutT8RGdC4ywC6Phup/view?usp=sharing'

# Extract the file ID
file_id = url.split('/')[-2]

# Construct the direct file access URL
file_url = 'https://drive.google.com/uc?id=' + file_id

clean_test = pd.read_csv(file_url)
clean_test

<ipython-input-10-8ea4dc28023f>:10: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  clean_test = pd.read_csv(file_url)

,Customer_ID,outlet_city,luxury_sales,fresh_sales,dry_sales,cluster_catgeory,outlet_city_encoded
0,10493832.0,Kelaniya,1209.60,756.00,5292.00,4,11
1,10178643.0,Moratuwa,1590.12,1060.08,6007.12,1,13
2,10513916.0,Wattala,2288.88,1481.04,9155.52,4,19
3,10334589.0,Wattala,2274.94,1739.66,9099.76,4,19
4,10458365.0,Kelaniya,2345.49,2069.55,9243.99,4,11
...,...,...,...,...,...,...,...
774150,10197979.0,Gampaha,3893.40,3893.40,3448.44,3,4
774151,10494575.0,Katunayake,6095.86,5557.99,6275.15,3,10
774152,10565682.0,Colombo,5121.42,4820.16,4669.53,3,1
774153,10351977.0,Kandy,6311.76,6311.76,5940.48,3,9
774154,10637635.0,Negombo,5833.50,6027.95,6611.30,3,14

In [11]:
# Original URL from Google Drive
url2 = 'https://drive.google.com/file/d/131d0T194QDySRy3GqdZzyY42YfLIEH43/view?usp=sharing'

# Extract the file ID
file_id2 = url.split('/')[-2]

# Construct the direct file access URL
file_url2 = 'https://drive.google.com/uc?id=' + file_id

clean_train = pd.read_csv(file_url2)
clean_train

<ipython-input-11-a0da36126032>:10: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  clean_train = pd.read_csv(file_url2)

,Customer_ID,outlet_city,luxury_sales,fresh_sales,dry_sales,cluster_catgeory,outlet_city_encoded
0,10493832.0,Kelaniya,1209.60,756.00,5292.00,4,11
1,10178643.0,Moratuwa,1590.12,1060.08,6007.12,1,13
2,10513916.0,Wattala,2288.88,1481.04,9155.52,4,19
3,10334589.0,Wattala,2274.94,1739.66,9099.76,4,19
4,10458365.0,Kelaniya,2345.49,2069.55,9243.99,4,11
...,...,...,...,...,...,...,...
774150,10197979.0,Gampaha,3893.40,3893.40,3448.44,3,4
774151,10494575.0,Katunayake,6095.86,5557.99,6275.15,3,10
774152,10565682.0,Colombo,5121.42,4820.16,4669.53,3,1
774153,10351977.0,Kandy,6311.76,6311.76,5940.48,3,9
774154,10637635.0,Negombo,5833.50,6027.95,6611.30,3,14

# **Logistic Regression - Baseline Model**

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, mean_squared_error, r2_score
from sklearn.impute import SimpleImputer

In [13]:
# Define X and y variables
X = clean_train[['luxury_sales', 'fresh_sales', 'dry_sales', 'outlet_city_encoded']]
y = clean_train['cluster_catgeory']

In [14]:
# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [16]:
# Initialize and train Logistic Regression model
log_reg_model = LogisticRegression(max_iter=1000, solver='saga', random_state=42)
log_reg_model.fit(X_train, y_train)

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [17]:
# Predict using test data
y_pred = log_reg_model.predict(X_test)

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [ ]:
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")
print(f"MSE: {mean_squared_error(y_test, y_pred):.4f}")
print(f"R2: {r2_score(y_test, y_pred):.4f}")

In [ ]:
# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
sns.heatmap(cm, annot=True, fmt='g')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

In [ ]:
# Classification Report
print(classification_report(y_test, y_pred))

# **KNN - Baseline Model**

In [ ]:
#Importing relevant libraries
from sklearn.neighbors import KNeighborsClassifier

In [18]:
#X, Y split
x = clean_train[['luxury_sales','fresh_sales','dry_sales','outlet_city_encoded']]
y = clean_train['cluster_catgeory']

In [19]:
# test, train split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

To optimize KNN model we need to find the n_neighbours and this is done by making use of the gridsearchCV system.

In [20]:
from sklearn.model_selection import GridSearchCV
#Define the parameter grid for n_neighbors
param_grid = {'n_neighbors': list(range(1, 10))}

#Create and fit the GridSearchCV object
grid = GridSearchCV(KNeighborsClassifier(algorithm='auto'), param_grid, cv=10, scoring='accuracy', n_jobs=-1)
grid.fit(x_train, y_train)

#Get the best n_neighbors value
best_k = grid.best_params_['n_neighbors']
print(f"Best k value: {best_k}")

NameError: name 'KNeighborsClassifier' is not defined

In [23]:
# Initialize KNN classifier
knn_model = KNeighborsClassifier(n_neighbors=7)

# Train the classifier
knn_model.fit(x_train, y_train)

NameError: name 'KNeighborsClassifier' is not defined

In [ ]:
# Predict labels for the test set
y_pred = knn_model.predict(x_test)

# Assuming you have y_test (true labels) and y_pred (predicted labels) from your KNN model
MSE = mean_squared_error(y_test, y_pred)
r2_ = r2_score(y_test, y_pred)
Acs = accuracy_score(y_test, y_pred)

print(f"MSE: {MSE}")
print(f"R2: {r2_}")
print(f"Accuracy: {Acs}")

In [ ]:
#Create a confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
sns.heatmap(cm, annot=True, fmt='g')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

In [ ]:
#classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

In [ ]:
# Predict cluster labels for the test data
y_predict = knn_model.predict(X_test)

# Analyze the distribution of predicted clusters
unique, counts = np.unique(y_predict, return_counts=True)
cluster_dist = dict(zip(unique, counts))

print("Distribution of Predicted Clusters:")
print(cluster_dist)

# Visualize the distribution
plt.figure(figsize=(8, 6))
plt.bar(cluster_dist.keys(), cluster_dist.values(), color='skyblue')
plt.xlabel("Cluster Label")
plt.ylabel("Number of Data Points")
plt.title("Distribution of Predicted Clusters in Test Data")
plt.show()

#**Decision Tree - Baseline Model**

In [ ]:
# Define X and y variables
x = clean_train[['luxury_sales', 'fresh_sales', 'dry_sales', 'outlet_city_encoded']]
y = clean_train['cluster_catgeory']

In [ ]:
x

In [24]:
y

0         4
1         1
2         4
3         4
4         4
         ..
774150    3
774151    3
774152    3
774153    3
774154    3
Name: cluster_catgeory, Length: 774155, dtype: object

In [25]:
# test, train split
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.25, random_state=1, stratify=y)

ValueError: Input contains NaN

In [28]:
#Train the decison tree model
from sklearn.tree import DecisionTreeClassifier
dt_d = DecisionTreeClassifier()
dt_d.fit(X_train, Y_train)

NameError: name 'Y_train' is not defined

In [ ]:
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")
print(f"MSE: {mean_squared_error(y_test, y_pred):.4f}")
print(f"R2: {r2_score(y_test, y_pred):.4f}")

In [ ]:
#Create a confusion matrix to analyse the performance of the DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
sns.heatmap(cm, annot=True, fmt='g')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

In [ ]:
#classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

In [ ]:
from sklearn import tree
fig, axes = plt.subplots(nrows=1, ncols=1, figsize=(9, 9), dpi=300)
tree.plot_tree(dt_d)
plt.show()

# **Random Forest - Baseline Model**

In [ ]:
# Checking for feature balance in the train data
clean_train['cluster_catgeory'].value_counts()

In [ ]:
# Importing code bloxks from the scikit learn library
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error, r2_score

Since customer Id has no prediction value and is only a unique identifier it is not included in the features in the x dataframe since including it migh lead to over fitting the model.

In [ ]:
# Difine X and Y variables
x = clean_train[['luxury_sales','fresh_sales','dry_sales','outlet_city_encoded']]
y = clean_train['cluster_catgeory']

In [ ]:
# test, train split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
# creating the randome forest classifier (rfc) model
rfc_model = RandomForestClassifier(n_estimators=25, random_state=42)

n_estimators is the hyperparameter in random forest which tells the number of decision trees in the forest. Higher n_estimators mean higher accuracy but also higher computational cost and time. Therefore, 25 has been settled on as the balance between accuracy, computational cost as futher increase in this hyper parameter would only provide dimnishing returns.

In [ ]:
# Train the model
rfc_model.fit(x_train, y_train)

In [ ]:
# Predict using the x_test data
y_pred = rfc_model.predict(x_test)

In [ ]:
# Evaluate the model
MSE = mean_squared_error(y_test, y_pred)
r2_= r2_score(y_test, y_pred)
Acs = accuracy_score(y_test, y_pred)

print(f"MSE:{MSE}")
print(f"R2:{r2_}")
print(f"Accuracy:{Acs}")

In [ ]:
# confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

In [ ]:
# heatmap of contribution matrix
sns.heatmap(cm, annot=True, fmt='g')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

In [ ]:
# importance of each feature
feature_importance = rfc_model.feature_importances_
features = x_train.columns

importance_df = pd.DataFrame({'Feature': features, 'Importance': feature_importance})
importance_df = importance_df.sort_values(by='Importance', ascending=False)

# plot
plt.figure(figsize=(10, 6))
sns.barplot(y='Importance', x='Feature', data=importance_df, hue='Feature')
plt.xlabel('Feature Importance')
plt.ylabel('Feature')
plt.title('Feature Importance')
plt.show()

In [ ]:
# classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

# **Gradient Boosting - Baseline Model**

In [ ]:
# Checking for feature balance in the train data
clean_train['cluster_catgeory'].value_counts()

In [ ]:
# Importing code bloxks from the scikit learn library
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [ ]:
# Difine X and Y variables
x = clean_train[['luxury_sales','fresh_sales','dry_sales','outlet_city_encoded']]
y = clean_train['cluster_catgeory']

In [ ]:
# test, train split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
# create the Gradient Boosting Classificatio (gbc) model
gbc_model = GradientBoostingClassifier(n_estimators=25, random_state=42)

In [ ]:
# Train the model
gbc_model.fit(x_train, y_train)

In [ ]:
# predict using the model
y_pred = gbc_model.predict(x_test)

In [ ]:
# Evaluate the model
MSE = mean_squared_error(y_test, y_pred)
r2_= r2_score(y_test, y_pred)
Acs = accuracy_score(y_test, y_pred)

print(f"MSE:{MSE}")
print(f"R2:{r2_}")
print(f"Accuracy:{Acs}")

In [ ]:
# confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

sns.heatmap(cm, annot=True, fmt='g')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

In [ ]:
# importance of each feature
feature_importance = gbc_model.feature_importances_
features = x_train.columns

importance_df = pd.DataFrame({'Feature': features, 'Importance': feature_importance})
importance_df = importance_df.sort_values(by='Importance', ascending=False)

# plot
plt.figure(figsize=(10, 6))
sns.barplot(y='Importance', x='Feature', data=importance_df, hue='Feature')
plt.xlabel('Feature Importance')
plt.ylabel('Feature')
plt.title('Feature Importance')
plt.show()

In [ ]:
# classification report
print(classification_report(y_test, y_pred))

# **Data Scaling**

## **Test**

In [33]:
# Original URL from Google Drive
url = 'https://drive.google.com/file/d/1KtSHNay_hiwqNUNutT8RGdC4ywC6Phup/view?usp=sharing'

# Extract the file ID
file_id = url.split('/')[-2]

# Construct the direct file access URL
file_url = 'https://drive.google.com/uc?id=' + file_id

clean_test = pd.read_csv(file_url)

<ipython-input-33-3e3d82857feb>:10: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  clean_test = pd.read_csv(file_url)

In [34]:
clean_test

,Customer_ID,outlet_city,luxury_sales,fresh_sales,dry_sales,cluster_catgeory,outlet_city_encoded
0,10493832.0,Kelaniya,1209.60,756.00,5292.00,4,11
1,10178643.0,Moratuwa,1590.12,1060.08,6007.12,1,13
2,10513916.0,Wattala,2288.88,1481.04,9155.52,4,19
3,10334589.0,Wattala,2274.94,1739.66,9099.76,4,19
4,10458365.0,Kelaniya,2345.49,2069.55,9243.99,4,11
...,...,...,...,...,...,...,...
774150,10197979.0,Gampaha,3893.40,3893.40,3448.44,3,4
774151,10494575.0,Katunayake,6095.86,5557.99,6275.15,3,10
774152,10565682.0,Colombo,5121.42,4820.16,4669.53,3,1
774153,10351977.0,Kandy,6311.76,6311.76,5940.48,3,9
774154,10637635.0,Negombo,5833.50,6027.95,6611.30,3,14

We are using the robust scaller since our data is skewed and luxury sales has outliers. Since this technique scales using the median and IQR it is best suited to deal with the skewness and the extreme values.

In [35]:
from sklearn.preprocessing import RobustScaler
# Identify numerical columns
numerical_columns = ['luxury_sales', 'fresh_sales', 'dry_sales']

# Initialize RobustScaler
DSPL_scaler = RobustScaler()

# Fit on training numerical data and transform both train & test
clean_test[numerical_columns] = DSPL_scaler.fit_transform(clean_test[numerical_columns])
clean_test

,Customer_ID,outlet_city,luxury_sales,fresh_sales,dry_sales,cluster_catgeory,outlet_city_encoded
0,10493832.0,Kelaniya,-0.449426,-0.514802,0.291061,4,11
1,10178643.0,Moratuwa,-0.111237,-0.454605,0.424125,1,13
2,10513916.0,Wattala,0.509791,-0.371270,1.009955,4,19
3,10334589.0,Wattala,0.497401,-0.320072,0.999579,4,19
4,10458365.0,Kelaniya,0.560103,-0.254766,1.026417,4,11
...,...,...,...,...,...,...,...
774150,10197979.0,Gampaha,1.935818,0.106291,-0.051974,3,4
774151,10494575.0,Katunayake,3.893269,0.435820,0.473998,3,10
774152,10565682.0,Colombo,3.027229,0.289756,0.175237,3,1
774153,10351977.0,Kandy,4.085152,0.585039,0.411726,3,9
774154,10637635.0,Negombo,3.660095,0.528855,0.536546,3,14

## **Train**

In [37]:
# Original URL from Google Drive
url2 = 'https://drive.google.com/file/d/131d0T194QDySRy3GqdZzyY42YfLIEH43/view?usp=sharing'

# Extract the file ID
file_id2 = url.split('/')[-2]

# Construct the direct file access URL
file_url2 = 'https://drive.google.com/uc?id=' + file_id

clean_train = pd.read_csv(file_url2)

<ipython-input-37-662b9525e4d5>:10: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  clean_train = pd.read_csv(file_url2)

In [38]:
clean_train

,Customer_ID,outlet_city,luxury_sales,fresh_sales,dry_sales,cluster_catgeory,outlet_city_encoded
0,10493832.0,Kelaniya,1209.60,756.00,5292.00,4,11
1,10178643.0,Moratuwa,1590.12,1060.08,6007.12,1,13
2,10513916.0,Wattala,2288.88,1481.04,9155.52,4,19
3,10334589.0,Wattala,2274.94,1739.66,9099.76,4,19
4,10458365.0,Kelaniya,2345.49,2069.55,9243.99,4,11
...,...,...,...,...,...,...,...
774150,10197979.0,Gampaha,3893.40,3893.40,3448.44,3,4
774151,10494575.0,Katunayake,6095.86,5557.99,6275.15,3,10
774152,10565682.0,Colombo,5121.42,4820.16,4669.53,3,1
774153,10351977.0,Kandy,6311.76,6311.76,5940.48,3,9
774154,10637635.0,Negombo,5833.50,6027.95,6611.30,3,14

We are using the robust scaller since our data is skewed and luxury sales has outliers. Since this technique scales using the median and IQR it is best suited to deal with the skewness and the extreme values.

In [39]:
from sklearn.preprocessing import RobustScaler
# Identify numerical columns
numerical_columns = ['luxury_sales', 'fresh_sales', 'dry_sales']

# Initialize RobustScaler
DSPL_scaler = RobustScaler()

# Fit on training numerical data and transform both train & test
clean_train[numerical_columns] = DSPL_scaler.fit_transform(clean_train[numerical_columns])
clean_train

,Customer_ID,outlet_city,luxury_sales,fresh_sales,dry_sales,cluster_catgeory,outlet_city_encoded
0,10493832.0,Kelaniya,-0.449426,-0.514802,0.291061,4,11
1,10178643.0,Moratuwa,-0.111237,-0.454605,0.424125,1,13
2,10513916.0,Wattala,0.509791,-0.371270,1.009955,4,19
3,10334589.0,Wattala,0.497401,-0.320072,0.999579,4,19
4,10458365.0,Kelaniya,0.560103,-0.254766,1.026417,4,11
...,...,...,...,...,...,...,...
774150,10197979.0,Gampaha,1.935818,0.106291,-0.051974,3,4
774151,10494575.0,Katunayake,3.893269,0.435820,0.473998,3,10
774152,10565682.0,Colombo,3.027229,0.289756,0.175237,3,1
774153,10351977.0,Kandy,4.085152,0.585039,0.411726,3,9
774154,10637635.0,Negombo,3.660095,0.528855,0.536546,3,14

# **Logistic Regression**

In [40]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, mean_squared_error, r2_score
from sklearn.impute import SimpleImputer

In [41]:
# Define X and y variables
X = clean_train[['luxury_sales', 'fresh_sales', 'dry_sales', 'outlet_city_encoded']]
y = clean_train['cluster_catgeory']

In [42]:
# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [43]:
# Initialize and train Logistic Regression model
log_reg_model = LogisticRegression(max_iter=1000, solver='saga', random_state=42)
log_reg_model.fit(X_train, y_train)

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [ ]:
# Predict using test data
y_pred = log_reg_model.predict(X_test)

In [ ]:
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")
print(f"MSE: {mean_squared_error(y_test, y_pred):.4f}")
print(f"R2: {r2_score(y_test, y_pred):.4f}")

In [ ]:
# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
sns.heatmap(cm, annot=True, fmt='g')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

In [ ]:
# Classification Report
print(classification_report(y_test, y_pred))

#**KNN Model**

In [ ]:
#Importing relevant libraries
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
#X, Y split
x = clean_train[['luxury_sales','fresh_sales','dry_sales','outlet_city_encoded']]
y = clean_train['cluster_catgeory']

In [ ]:
# test, train split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

To optimize KNN model we need to find the n_neighbours and this is done by making use of the gridsearchCV system.

In [ ]:
from sklearn.model_selection import GridSearchCV
#Define the parameter grid for n_neighbors
param_grid = {'n_neighbors': list(range(1, 10))}

#Create and fit the GridSearchCV object
grid = GridSearchCV(KNeighborsClassifier(algorithm='auto'), param_grid, cv=10, scoring='accuracy', n_jobs=-1)
grid.fit(x_train, y_train)

#Get the best n_neighbors value
best_k = grid.best_params_['n_neighbors']
print(f"Best k value: {best_k}")

In [ ]:
# Initialize KNN classifier
knn_model = KNeighborsClassifier(n_neighbors=7)

# Train the classifier
knn_model.fit(x_train, y_train)

In [ ]:
# Predict labels for the test set
y_pred = knn_model.predict(x_test)

# Assuming you have y_test (true labels) and y_pred (predicted labels) from your KNN model
MSE = mean_squared_error(y_test, y_pred)
r2_ = r2_score(y_test, y_pred)
Acs = accuracy_score(y_test, y_pred)

print(f"MSE: {MSE}")
print(f"R2: {r2_}")
print(f"Accuracy: {Acs}")

In [ ]:
#Create a confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
sns.heatmap(cm, annot=True, fmt='g')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

In [ ]:
#classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

In [ ]:
# Predict cluster labels for the test data
y_predict = knn_model.predict(X_test)

# Analyze the distribution of predicted clusters
unique, counts = np.unique(y_predict, return_counts=True)
cluster_dist = dict(zip(unique, counts))

print("Distribution of Predicted Clusters:")
print(cluster_dist)

# Visualize the distribution
plt.figure(figsize=(8, 6))
plt.bar(cluster_dist.keys(), cluster_dist.values(), color='skyblue')
plt.xlabel("Cluster Label")
plt.ylabel("Number of Data Points")
plt.title("Distribution of Predicted Clusters in Test Data")
plt.show()

# **Decsion Tree Model**

In [44]:
# Define X and y variables
x = clean_train[['luxury_sales', 'fresh_sales', 'dry_sales', 'outlet_city_encoded']]
y = clean_train['cluster_catgeory']

In [45]:
x

        luxury_sales  fresh_sales  dry_sales  outlet_city_encoded
0          -0.449426    -0.514802   0.291061                   11
1          -0.111237    -0.454605   0.424125                   13
2           0.509791    -0.371270   1.009955                   19
3           0.497401    -0.320072   0.999579                   19
4           0.560103    -0.254766   1.026417                   11
...              ...          ...        ...                  ...
774150      1.935818     0.106291  -0.051974                    4
774151      3.893269     0.435820   0.473998                   10
774152      3.027229     0.289756   0.175237                    1
774153      4.085152     0.585039   0.411726                    9
774154      3.660095     0.528855   0.536546                   14

[774155 rows x 4 columns]

In [46]:
y

0         4
1         1
2         4
3         4
4         4
         ..
774150    3
774151    3
774152    3
774153    3
774154    3
Name: cluster_catgeory, Length: 774155, dtype: object

In [47]:
# test, train split
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.25, random_state=1, stratify=y)

ValueError: Input contains NaN

In [ ]:
#Train the decison tree model
from sklearn.tree import DecisionTreeClassifier
dt_d = DecisionTreeClassifier()
dt_d.fit(X_train, Y_train)

In [ ]:
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")
print(f"MSE: {mean_squared_error(y_test, y_pred):.4f}")
print(f"R2: {r2_score(y_test, y_pred):.4f}")

In [ ]:
#Create a confusion matrix to analyse the performance of the DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
sns.heatmap(cm, annot=True, fmt='g')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

In [ ]:
#classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

In [ ]:
#Plotting the decsion tree
from sklearn import tree
fig, axes = plt.subplots(nrows=1, ncols=1, figsize=(9, 9), dpi=300)
tree.plot_tree(dt_d)
plt.show()

#**Random Forest Model**

In [ ]:
# Checking for feature balance in the train data
clean_train['cluster_catgeory'].value_counts()

In [ ]:
# Importing code bloxks from the scikit learn library
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error, r2_score

Since customer Id has no prediction value and is only a unique identifier it is not included in the features in the x dataframe since including it migh lead to over fitting the model.

In [ ]:
# Difine X and Y variables
x = clean_train[['luxury_sales','fresh_sales','dry_sales','outlet_city_encoded']]
y = clean_train['cluster_catgeory']

In [ ]:
# test, train split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
# creating the randome forest classifier (rfc) model
rfc_model = RandomForestClassifier(n_estimators=25, random_state=42)

n_estimators is the hyperparameter in random forest which tells the number of decision trees in the forest. Higher n_estimators mean higher accuracy but also higher computational cost and time. Therefore, 25 has been settled on as the balance between accuracy, computational cost as futher increase in this hyper parameter would only provide dimnishing returns.

In [ ]:
# Train the model
rfc_model.fit(x_train, y_train)

In [ ]:
# Predict using the x_test data
y_pred = rfc_model.predict(x_test)

In [ ]:
# Evaluate the model
MSE = mean_squared_error(y_test, y_pred)
r2_= r2_score(y_test, y_pred)
Acs = accuracy_score(y_test, y_pred)

print(f"MSE:{MSE}")
print(f"R2:{r2_}")
print(f"Accuracy:{Acs}")

In [ ]:
# confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

In [ ]:
# heatmap of contribution matrix
sns.heatmap(cm, annot=True, fmt='g')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

In [ ]:
# importance of each feature
feature_importance = rfc_model.feature_importances_
features = x_train.columns

importance_df = pd.DataFrame({'Feature': features, 'Importance': feature_importance})
importance_df = importance_df.sort_values(by='Importance', ascending=False)

# plot
plt.figure(figsize=(10, 6))
sns.barplot(y='Importance', x='Feature', data=importance_df, hue='Feature')
plt.xlabel('Feature Importance')
plt.ylabel('Feature')
plt.title('Feature Importance')
plt.show()

In [ ]:
# classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

# **Gradient Boosting Model**

In [ ]:
# Checking for feature balance in the train data
clean_train['cluster_catgeory'].value_counts()

In [ ]:
# Importing code bloxks from the scikit learn library
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [ ]:
# Difine X and Y variables
x = clean_train[['luxury_sales','fresh_sales','dry_sales','outlet_city_encoded']]
y = clean_train['cluster_catgeory']

In [ ]:
# test, train split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
# create the Gradient Boosting Classificatio (gbc) model
gbc_model = GradientBoostingClassifier(n_estimators=25, random_state=42)

In [ ]:
# Train the model
gbc_model.fit(x_train, y_train)

In [ ]:
# predict using the model
y_pred = gbc_model.predict(x_test)

In [ ]:
# Evaluate the model
MSE = mean_squared_error(y_test, y_pred)
r2_= r2_score(y_test, y_pred)
Acs = accuracy_score(y_test, y_pred)

print(f"MSE:{MSE}")
print(f"R2:{r2_}")
print(f"Accuracy:{Acs}")

In [ ]:
# confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

sns.heatmap(cm, annot=True, fmt='g')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

In [ ]:
# importance of each feature
feature_importance = gbc_model.feature_importances_
features = x_train.columns

importance_df = pd.DataFrame({'Feature': features, 'Importance': feature_importance})
importance_df = importance_df.sort_values(by='Importance', ascending=False)

# plot
plt.figure(figsize=(10, 6))
sns.barplot(y='Importance', x='Feature', data=importance_df, hue='Feature')
plt.xlabel('Feature Importance')
plt.ylabel('Feature')
plt.title('Feature Importance')
plt.show()

In [ ]:
# classification report
print(classification_report(y_test, y_pred))